qgc_plan_path: "/home/radhouene/autosoaring_app/src/autosoaring_pkg/config/area2.plan"
num_thermals: 12
min_distance_between_thermals: 200.0
zi_range: [1250.0, 1250.0]       
w_star_range: [5,5]         
lifespan_range: [1200000.0, 1800000.0] 
